//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 10:15:44 AM CST 
//


package org.meveo.asg.api.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.meveo.asg.api.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TaxDeleted_QNAME = new QName("", "TaxDeleted");
    private final static QName _UpdateOrganizationSubscriptionWithCreditLimitResponse_QNAME = new QName("", "UpdateOrganizationSubscriptionWithCreditLimitResponse");
    private final static QName _OfferEventData_QNAME = new QName("", "OfferEventData");
    private final static QName _SubscriptionChargeData_QNAME = new QName("", "SubscriptionChargeData");
    private final static QName _ServiceItemData_QNAME = new QName("", "ServiceItemData");
    private final static QName _TerminateOrganizationSubscriptionResponse_QNAME = new QName("", "TerminateOrganizationSubscriptionResponse");
    private final static QName _OrganizationUpdated_QNAME = new QName("", "OrganizationUpdated");
    private final static QName _OfferPricePlanDeleted_QNAME = new QName("", "OfferPricePlanDeleted");
    private final static QName _ServicePricePlanUpdated_QNAME = new QName("", "ServicePricePlanUpdated");
    private final static QName _SubscriptionAgeRangeChargeData_QNAME = new QName("", "SubscriptionAgeRangeChargeData");
    private final static QName _UserDeleted_QNAME = new QName("", "UserDeleted");
    private final static QName _ServiceCreated_QNAME = new QName("", "ServiceCreated");
    private final static QName _TaxCreated_QNAME = new QName("", "TaxCreated");
    private final static QName _PricePlanEventData_QNAME = new QName("", "PricePlanEventData");
    private final static QName _QuantityRangeChargeData_QNAME = new QName("", "QuantityRangeChargeData");
    private final static QName _OfferDeleted_QNAME = new QName("", "OfferDeleted");
    private final static QName _ServicePricePlanCreated_QNAME = new QName("", "ServicePricePlanCreated");
    private final static QName _CreateUserSubscriptionWithCreditLimitRequest_QNAME = new QName("", "CreateUserSubscriptionWithCreditLimitRequest");
    private final static QName _OfferPricePlanUpdated_QNAME = new QName("", "OfferPricePlanUpdated");
    private final static QName _PlaceOrderRequest_QNAME = new QName("", "PlaceOrderRequest");
    private final static QName _UpdateOrganizationSubscriptionWithCreditLimitRequest_QNAME = new QName("", "UpdateOrganizationSubscriptionWithCreditLimitRequest");
    private final static QName _BaseEventData_QNAME = new QName("", "BaseEventData");
    private final static QName _TerminateOrganizationSubscriptionRequest_QNAME = new QName("", "TerminateOrganizationSubscriptionRequest");
    private final static QName _ServiceEventData_QNAME = new QName("", "ServiceEventData");
    private final static QName _ServiceSubscriptionDate_QNAME = new QName("", "ServiceSubscriptionDate");
    private final static QName _CancelUserSubscriptionRequest_QNAME = new QName("", "CancelUserSubscriptionRequest");
    private final static QName _UserEventData_QNAME = new QName("", "UserEventData");
    private final static QName _RegionDeleted_QNAME = new QName("", "RegionDeleted");
    private final static QName _UsageRangeChargeData_QNAME = new QName("", "UsageRangeChargeData");
    private final static QName _ItemDescriptionData_QNAME = new QName("", "ItemDescriptionData");
    private final static QName _ServiceDeleted_QNAME = new QName("", "ServiceDeleted");
    private final static QName _ChargePriceData_QNAME = new QName("", "ChargePriceData");
    private final static QName _OrganizationCreated_QNAME = new QName("", "OrganizationCreated");
    private final static QName _UpdateSubscriptionWithCreditLimitResponseBase_QNAME = new QName("", "UpdateSubscriptionWithCreditLimitResponseBase");
    private final static QName _CreateUserSubscriptionWithCreditLimitResponse_QNAME = new QName("", "CreateUserSubscriptionWithCreditLimitResponse");
    private final static QName _ItemNameData_QNAME = new QName("", "ItemNameData");
    private final static QName _TerminationChargeData_QNAME = new QName("", "TerminationChargeData");
    private final static QName _CancelOrganizationSubscriptionResponse_QNAME = new QName("", "CancelOrganizationSubscriptionResponse");
    private final static QName _TerminateSubscriptionRequestBase_QNAME = new QName("", "TerminateSubscriptionRequestBase");
    private final static QName _CancelUserSubscriptionResponse_QNAME = new QName("", "CancelUserSubscriptionResponse");
    private final static QName _TaxEventData_QNAME = new QName("", "TaxEventData");
    private final static QName _MutexItemData_QNAME = new QName("", "MutexItemData");
    private final static QName _UserCreated_QNAME = new QName("", "UserCreated");
    private final static QName _TaxData_QNAME = new QName("", "TaxData");
    private final static QName _UpdateUserSubscriptionWithCreditLimitRequest_QNAME = new QName("", "UpdateUserSubscriptionWithCreditLimitRequest");
    private final static QName _OfferUpdated_QNAME = new QName("", "OfferUpdated");
    private final static QName _TerminateSubscriptionResponseBase_QNAME = new QName("", "TerminateSubscriptionResponseBase");
    private final static QName _RegionCreated_QNAME = new QName("", "RegionCreated");
    private final static QName _CreateSubscriptionWithCreditLimitResponseBase_QNAME = new QName("", "CreateSubscriptionWithCreditLimitResponseBase");
    private final static QName _ServicePricePlanDeleted_QNAME = new QName("", "ServicePricePlanDeleted");
    private final static QName _TerminateUserSubscriptionRequest_QNAME = new QName("", "TerminateUserSubscriptionRequest");
    private final static QName _UsageChargeData_QNAME = new QName("", "UsageChargeData");
    private final static QName _RecurringChargeData_QNAME = new QName("", "RecurringChargeData");
    private final static QName _TerminateUserSubscriptionResponse_QNAME = new QName("", "TerminateUserSubscriptionResponse");
    private final static QName _ChargeBaseData_QNAME = new QName("", "ChargeBaseData");
    private final static QName _CreateOrganizationSubscriptionWithCreditLimitResponse_QNAME = new QName("", "CreateOrganizationSubscriptionWithCreditLimitResponse");
    private final static QName _CancelSubscriptionRequestBase_QNAME = new QName("", "CancelSubscriptionRequestBase");
    private final static QName _OrganizationEventData_QNAME = new QName("", "OrganizationEventData");
    private final static QName _UpdateSubscriptionWithCreditLimitRequestBase_QNAME = new QName("", "UpdateSubscriptionWithCreditLimitRequestBase");
    private final static QName _UserUpdated_QNAME = new QName("", "UserUpdated");
    private final static QName _CreateSubscriptionWithCreditLimitRequestBase_QNAME = new QName("", "CreateSubscriptionWithCreditLimitRequestBase");
    private final static QName _RegionUpdated_QNAME = new QName("", "RegionUpdated");
    private final static QName _OfferCreated_QNAME = new QName("", "OfferCreated");
    private final static QName _OfferPricePlanCreated_QNAME = new QName("", "OfferPricePlanCreated");
    private final static QName _TaxUpdated_QNAME = new QName("", "TaxUpdated");
    private final static QName _RegionEventData_QNAME = new QName("", "RegionEventData");
    private final static QName _CreateOrganizationSubscriptionWithCreditLimitRequest_QNAME = new QName("", "CreateOrganizationSubscriptionWithCreditLimitRequest");
    private final static QName _CancelSubscriptionResponseBase_QNAME = new QName("", "CancelSubscriptionResponseBase");
    private final static QName _ServiceUpdated_QNAME = new QName("", "ServiceUpdated");
    private final static QName _CancelOrganizationSubscriptionRequest_QNAME = new QName("", "CancelOrganizationSubscriptionRequest");
    private final static QName _OrganizationDeleted_QNAME = new QName("", "OrganizationDeleted");
    private final static QName _UpdateUserSubscriptionWithCreditLimitResponse_QNAME = new QName("", "UpdateUserSubscriptionWithCreditLimitResponse");
    private final static QName _OrganizationCreditLimit_QNAME = new QName("", "OrganizationCreditLimit");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.meveo.asg.api.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaxDeleted }
     * 
     */
    public TaxDeleted createTaxDeleted() {
        return new TaxDeleted();
    }

    /**
     * Create an instance of {@link UpdateOrganizationSubscriptionWithCreditLimitResponse }
     * 
     */
    public UpdateOrganizationSubscriptionWithCreditLimitResponse createUpdateOrganizationSubscriptionWithCreditLimitResponse() {
        return new UpdateOrganizationSubscriptionWithCreditLimitResponse();
    }

    /**
     * Create an instance of {@link OfferEventData }
     * 
     */
    public OfferEventData createOfferEventData() {
        return new OfferEventData();
    }

    /**
     * Create an instance of {@link SubscriptionChargeData }
     * 
     */
    public SubscriptionChargeData createSubscriptionChargeData() {
        return new SubscriptionChargeData();
    }

    /**
     * Create an instance of {@link ServiceItemData }
     * 
     */
    public ServiceItemData createServiceItemData() {
        return new ServiceItemData();
    }

    /**
     * Create an instance of {@link TerminateOrganizationSubscriptionResponse }
     * 
     */
    public TerminateOrganizationSubscriptionResponse createTerminateOrganizationSubscriptionResponse() {
        return new TerminateOrganizationSubscriptionResponse();
    }

    /**
     * Create an instance of {@link OrganizationUpdated }
     * 
     */
    public OrganizationUpdated createOrganizationUpdated() {
        return new OrganizationUpdated();
    }

    /**
     * Create an instance of {@link OfferPricePlanDeleted }
     * 
     */
    public OfferPricePlanDeleted createOfferPricePlanDeleted() {
        return new OfferPricePlanDeleted();
    }

    /**
     * Create an instance of {@link ServicePricePlanUpdated }
     * 
     */
    public ServicePricePlanUpdated createServicePricePlanUpdated() {
        return new ServicePricePlanUpdated();
    }

    /**
     * Create an instance of {@link SubscriptionAgeRangeChargeData }
     * 
     */
    public SubscriptionAgeRangeChargeData createSubscriptionAgeRangeChargeData() {
        return new SubscriptionAgeRangeChargeData();
    }

    /**
     * Create an instance of {@link UserDeleted }
     * 
     */
    public UserDeleted createUserDeleted() {
        return new UserDeleted();
    }

    /**
     * Create an instance of {@link ServiceCreated }
     * 
     */
    public ServiceCreated createServiceCreated() {
        return new ServiceCreated();
    }

    /**
     * Create an instance of {@link TaxCreated }
     * 
     */
    public TaxCreated createTaxCreated() {
        return new TaxCreated();
    }

    /**
     * Create an instance of {@link PricePlanEventData }
     * 
     */
    public PricePlanEventData createPricePlanEventData() {
        return new PricePlanEventData();
    }

    /**
     * Create an instance of {@link QuantityRangeChargeData }
     * 
     */
    public QuantityRangeChargeData createQuantityRangeChargeData() {
        return new QuantityRangeChargeData();
    }

    /**
     * Create an instance of {@link OfferDeleted }
     * 
     */
    public OfferDeleted createOfferDeleted() {
        return new OfferDeleted();
    }

    /**
     * Create an instance of {@link ServicePricePlanCreated }
     * 
     */
    public ServicePricePlanCreated createServicePricePlanCreated() {
        return new ServicePricePlanCreated();
    }

    /**
     * Create an instance of {@link CreateUserSubscriptionWithCreditLimitRequest }
     * 
     */
    public CreateUserSubscriptionWithCreditLimitRequest createCreateUserSubscriptionWithCreditLimitRequest() {
        return new CreateUserSubscriptionWithCreditLimitRequest();
    }

    /**
     * Create an instance of {@link OfferPricePlanUpdated }
     * 
     */
    public OfferPricePlanUpdated createOfferPricePlanUpdated() {
        return new OfferPricePlanUpdated();
    }

    /**
     * Create an instance of {@link UpdateOrganizationSubscriptionWithCreditLimitRequest }
     * 
     */
    public UpdateOrganizationSubscriptionWithCreditLimitRequest createUpdateOrganizationSubscriptionWithCreditLimitRequest() {
        return new UpdateOrganizationSubscriptionWithCreditLimitRequest();
    }

    /**
     * Create an instance of {@link PlaceOrderRequest }
     * 
     */
    public PlaceOrderRequest createPlaceOrderRequest() {
        return new PlaceOrderRequest();
    }

    /**
     * Create an instance of {@link BaseEventData }
     * 
     */
    public BaseEventData createBaseEventData() {
        return new BaseEventData();
    }

    /**
     * Create an instance of {@link TerminateOrganizationSubscriptionRequest }
     * 
     */
    public TerminateOrganizationSubscriptionRequest createTerminateOrganizationSubscriptionRequest() {
        return new TerminateOrganizationSubscriptionRequest();
    }

    /**
     * Create an instance of {@link ServiceEventData }
     * 
     */
    public ServiceEventData createServiceEventData() {
        return new ServiceEventData();
    }

    /**
     * Create an instance of {@link ServiceSubscriptionDate }
     * 
     */
    public ServiceSubscriptionDate createServiceSubscriptionDate() {
        return new ServiceSubscriptionDate();
    }

    /**
     * Create an instance of {@link CancelUserSubscriptionRequest }
     * 
     */
    public CancelUserSubscriptionRequest createCancelUserSubscriptionRequest() {
        return new CancelUserSubscriptionRequest();
    }

    /**
     * Create an instance of {@link UserEventData }
     * 
     */
    public UserEventData createUserEventData() {
        return new UserEventData();
    }

    /**
     * Create an instance of {@link RegionDeleted }
     * 
     */
    public RegionDeleted createRegionDeleted() {
        return new RegionDeleted();
    }

    /**
     * Create an instance of {@link UsageRangeChargeData }
     * 
     */
    public UsageRangeChargeData createUsageRangeChargeData() {
        return new UsageRangeChargeData();
    }

    /**
     * Create an instance of {@link ItemDescriptionData }
     * 
     */
    public ItemDescriptionData createItemDescriptionData() {
        return new ItemDescriptionData();
    }

    /**
     * Create an instance of {@link ServiceDeleted }
     * 
     */
    public ServiceDeleted createServiceDeleted() {
        return new ServiceDeleted();
    }

    /**
     * Create an instance of {@link ChargePriceData }
     * 
     */
    public ChargePriceData createChargePriceData() {
        return new ChargePriceData();
    }

    /**
     * Create an instance of {@link OrganizationCreated }
     * 
     */
    public OrganizationCreated createOrganizationCreated() {
        return new OrganizationCreated();
    }

    /**
     * Create an instance of {@link CreateUserSubscriptionWithCreditLimitResponse }
     * 
     */
    public CreateUserSubscriptionWithCreditLimitResponse createCreateUserSubscriptionWithCreditLimitResponse() {
        return new CreateUserSubscriptionWithCreditLimitResponse();
    }

    /**
     * Create an instance of {@link ItemNameData }
     * 
     */
    public ItemNameData createItemNameData() {
        return new ItemNameData();
    }

    /**
     * Create an instance of {@link TerminationChargeData }
     * 
     */
    public TerminationChargeData createTerminationChargeData() {
        return new TerminationChargeData();
    }

    /**
     * Create an instance of {@link CancelOrganizationSubscriptionResponse }
     * 
     */
    public CancelOrganizationSubscriptionResponse createCancelOrganizationSubscriptionResponse() {
        return new CancelOrganizationSubscriptionResponse();
    }

    /**
     * Create an instance of {@link CancelUserSubscriptionResponse }
     * 
     */
    public CancelUserSubscriptionResponse createCancelUserSubscriptionResponse() {
        return new CancelUserSubscriptionResponse();
    }

    /**
     * Create an instance of {@link TaxEventData }
     * 
     */
    public TaxEventData createTaxEventData() {
        return new TaxEventData();
    }

    /**
     * Create an instance of {@link MutexItemData }
     * 
     */
    public MutexItemData createMutexItemData() {
        return new MutexItemData();
    }

    /**
     * Create an instance of {@link UserCreated }
     * 
     */
    public UserCreated createUserCreated() {
        return new UserCreated();
    }

    /**
     * Create an instance of {@link TaxData }
     * 
     */
    public TaxData createTaxData() {
        return new TaxData();
    }

    /**
     * Create an instance of {@link UpdateUserSubscriptionWithCreditLimitRequest }
     * 
     */
    public UpdateUserSubscriptionWithCreditLimitRequest createUpdateUserSubscriptionWithCreditLimitRequest() {
        return new UpdateUserSubscriptionWithCreditLimitRequest();
    }

    /**
     * Create an instance of {@link OfferUpdated }
     * 
     */
    public OfferUpdated createOfferUpdated() {
        return new OfferUpdated();
    }

    /**
     * Create an instance of {@link RegionCreated }
     * 
     */
    public RegionCreated createRegionCreated() {
        return new RegionCreated();
    }

    /**
     * Create an instance of {@link ServicePricePlanDeleted }
     * 
     */
    public ServicePricePlanDeleted createServicePricePlanDeleted() {
        return new ServicePricePlanDeleted();
    }

    /**
     * Create an instance of {@link TerminateUserSubscriptionRequest }
     * 
     */
    public TerminateUserSubscriptionRequest createTerminateUserSubscriptionRequest() {
        return new TerminateUserSubscriptionRequest();
    }

    /**
     * Create an instance of {@link RecurringChargeData }
     * 
     */
    public RecurringChargeData createRecurringChargeData() {
        return new RecurringChargeData();
    }

    /**
     * Create an instance of {@link UsageChargeData }
     * 
     */
    public UsageChargeData createUsageChargeData() {
        return new UsageChargeData();
    }

    /**
     * Create an instance of {@link TerminateUserSubscriptionResponse }
     * 
     */
    public TerminateUserSubscriptionResponse createTerminateUserSubscriptionResponse() {
        return new TerminateUserSubscriptionResponse();
    }

    /**
     * Create an instance of {@link CreateOrganizationSubscriptionWithCreditLimitResponse }
     * 
     */
    public CreateOrganizationSubscriptionWithCreditLimitResponse createCreateOrganizationSubscriptionWithCreditLimitResponse() {
        return new CreateOrganizationSubscriptionWithCreditLimitResponse();
    }

    /**
     * Create an instance of {@link OrganizationEventData }
     * 
     */
    public OrganizationEventData createOrganizationEventData() {
        return new OrganizationEventData();
    }

    /**
     * Create an instance of {@link UserUpdated }
     * 
     */
    public UserUpdated createUserUpdated() {
        return new UserUpdated();
    }

    /**
     * Create an instance of {@link RegionUpdated }
     * 
     */
    public RegionUpdated createRegionUpdated() {
        return new RegionUpdated();
    }

    /**
     * Create an instance of {@link OfferPricePlanCreated }
     * 
     */
    public OfferPricePlanCreated createOfferPricePlanCreated() {
        return new OfferPricePlanCreated();
    }

    /**
     * Create an instance of {@link OfferCreated }
     * 
     */
    public OfferCreated createOfferCreated() {
        return new OfferCreated();
    }

    /**
     * Create an instance of {@link TaxUpdated }
     * 
     */
    public TaxUpdated createTaxUpdated() {
        return new TaxUpdated();
    }

    /**
     * Create an instance of {@link CreateOrganizationSubscriptionWithCreditLimitRequest }
     * 
     */
    public CreateOrganizationSubscriptionWithCreditLimitRequest createCreateOrganizationSubscriptionWithCreditLimitRequest() {
        return new CreateOrganizationSubscriptionWithCreditLimitRequest();
    }

    /**
     * Create an instance of {@link RegionEventData }
     * 
     */
    public RegionEventData createRegionEventData() {
        return new RegionEventData();
    }

    /**
     * Create an instance of {@link ServiceUpdated }
     * 
     */
    public ServiceUpdated createServiceUpdated() {
        return new ServiceUpdated();
    }

    /**
     * Create an instance of {@link OrganizationDeleted }
     * 
     */
    public OrganizationDeleted createOrganizationDeleted() {
        return new OrganizationDeleted();
    }

    /**
     * Create an instance of {@link CancelOrganizationSubscriptionRequest }
     * 
     */
    public CancelOrganizationSubscriptionRequest createCancelOrganizationSubscriptionRequest() {
        return new CancelOrganizationSubscriptionRequest();
    }

    /**
     * Create an instance of {@link UpdateUserSubscriptionWithCreditLimitResponse }
     * 
     */
    public UpdateUserSubscriptionWithCreditLimitResponse createUpdateUserSubscriptionWithCreditLimitResponse() {
        return new UpdateUserSubscriptionWithCreditLimitResponse();
    }

    /**
     * Create an instance of {@link OrganizationCreditLimit }
     * 
     */
    public OrganizationCreditLimit createOrganizationCreditLimit() {
        return new OrganizationCreditLimit();
    }

    /**
     * Create an instance of {@link ArrayOfMutexItemData }
     * 
     */
    public ArrayOfMutexItemData createArrayOfMutexItemData() {
        return new ArrayOfMutexItemData();
    }

    /**
     * Create an instance of {@link ArrayOfServiceItemData }
     * 
     */
    public ArrayOfServiceItemData createArrayOfServiceItemData() {
        return new ArrayOfServiceItemData();
    }

    /**
     * Create an instance of {@link ArrayOfChargePriceData }
     * 
     */
    public ArrayOfChargePriceData createArrayOfChargePriceData() {
        return new ArrayOfChargePriceData();
    }

    /**
     * Create an instance of {@link ArrayOfItemDescriptionData }
     * 
     */
    public ArrayOfItemDescriptionData createArrayOfItemDescriptionData() {
        return new ArrayOfItemDescriptionData();
    }

    /**
     * Create an instance of {@link ArrayOfTaxData }
     * 
     */
    public ArrayOfTaxData createArrayOfTaxData() {
        return new ArrayOfTaxData();
    }

    /**
     * Create an instance of {@link ArrayOfServiceSubscriptionDate }
     * 
     */
    public ArrayOfServiceSubscriptionDate createArrayOfServiceSubscriptionDate() {
        return new ArrayOfServiceSubscriptionDate();
    }

    /**
     * Create an instance of {@link ArrayOfUsageRangeChargeData }
     * 
     */
    public ArrayOfUsageRangeChargeData createArrayOfUsageRangeChargeData() {
        return new ArrayOfUsageRangeChargeData();
    }

    /**
     * Create an instance of {@link ArrayOfQuantityRangeChargeData }
     * 
     */
    public ArrayOfQuantityRangeChargeData createArrayOfQuantityRangeChargeData() {
        return new ArrayOfQuantityRangeChargeData();
    }

    /**
     * Create an instance of {@link ArrayOfItemNameData }
     * 
     */
    public ArrayOfItemNameData createArrayOfItemNameData() {
        return new ArrayOfItemNameData();
    }

    /**
     * Create an instance of {@link ArrayOfSubscriptionAgeRangeChargeData }
     * 
     */
    public ArrayOfSubscriptionAgeRangeChargeData createArrayOfSubscriptionAgeRangeChargeData() {
        return new ArrayOfSubscriptionAgeRangeChargeData();
    }

    /**
     * Create an instance of {@link ArrayOfGuid }
     * 
     */
    public ArrayOfGuid createArrayOfGuid() {
        return new ArrayOfGuid();
    }

    /**
     * Create an instance of {@link ArrayOfOrganizationCreditLimit }
     * 
     */
    public ArrayOfOrganizationCreditLimit createArrayOfOrganizationCreditLimit() {
        return new ArrayOfOrganizationCreditLimit();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TaxDeleted")
    public JAXBElement<TaxDeleted> createTaxDeleted(TaxDeleted value) {
        return new JAXBElement<TaxDeleted>(_TaxDeleted_QNAME, TaxDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateOrganizationSubscriptionWithCreditLimitResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdateOrganizationSubscriptionWithCreditLimitResponse")
    public JAXBElement<UpdateOrganizationSubscriptionWithCreditLimitResponse> createUpdateOrganizationSubscriptionWithCreditLimitResponse(UpdateOrganizationSubscriptionWithCreditLimitResponse value) {
        return new JAXBElement<UpdateOrganizationSubscriptionWithCreditLimitResponse>(_UpdateOrganizationSubscriptionWithCreditLimitResponse_QNAME, UpdateOrganizationSubscriptionWithCreditLimitResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferEventData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfferEventData")
    public JAXBElement<OfferEventData> createOfferEventData(OfferEventData value) {
        return new JAXBElement<OfferEventData>(_OfferEventData_QNAME, OfferEventData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscriptionChargeData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubscriptionChargeData")
    public JAXBElement<SubscriptionChargeData> createSubscriptionChargeData(SubscriptionChargeData value) {
        return new JAXBElement<SubscriptionChargeData>(_SubscriptionChargeData_QNAME, SubscriptionChargeData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceItemData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceItemData")
    public JAXBElement<ServiceItemData> createServiceItemData(ServiceItemData value) {
        return new JAXBElement<ServiceItemData>(_ServiceItemData_QNAME, ServiceItemData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminateOrganizationSubscriptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TerminateOrganizationSubscriptionResponse")
    public JAXBElement<TerminateOrganizationSubscriptionResponse> createTerminateOrganizationSubscriptionResponse(TerminateOrganizationSubscriptionResponse value) {
        return new JAXBElement<TerminateOrganizationSubscriptionResponse>(_TerminateOrganizationSubscriptionResponse_QNAME, TerminateOrganizationSubscriptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OrganizationUpdated")
    public JAXBElement<OrganizationUpdated> createOrganizationUpdated(OrganizationUpdated value) {
        return new JAXBElement<OrganizationUpdated>(_OrganizationUpdated_QNAME, OrganizationUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferPricePlanDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfferPricePlanDeleted")
    public JAXBElement<OfferPricePlanDeleted> createOfferPricePlanDeleted(OfferPricePlanDeleted value) {
        return new JAXBElement<OfferPricePlanDeleted>(_OfferPricePlanDeleted_QNAME, OfferPricePlanDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServicePricePlanUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServicePricePlanUpdated")
    public JAXBElement<ServicePricePlanUpdated> createServicePricePlanUpdated(ServicePricePlanUpdated value) {
        return new JAXBElement<ServicePricePlanUpdated>(_ServicePricePlanUpdated_QNAME, ServicePricePlanUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscriptionAgeRangeChargeData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubscriptionAgeRangeChargeData")
    public JAXBElement<SubscriptionAgeRangeChargeData> createSubscriptionAgeRangeChargeData(SubscriptionAgeRangeChargeData value) {
        return new JAXBElement<SubscriptionAgeRangeChargeData>(_SubscriptionAgeRangeChargeData_QNAME, SubscriptionAgeRangeChargeData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserDeleted")
    public JAXBElement<UserDeleted> createUserDeleted(UserDeleted value) {
        return new JAXBElement<UserDeleted>(_UserDeleted_QNAME, UserDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceCreated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceCreated")
    public JAXBElement<ServiceCreated> createServiceCreated(ServiceCreated value) {
        return new JAXBElement<ServiceCreated>(_ServiceCreated_QNAME, ServiceCreated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxCreated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TaxCreated")
    public JAXBElement<TaxCreated> createTaxCreated(TaxCreated value) {
        return new JAXBElement<TaxCreated>(_TaxCreated_QNAME, TaxCreated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PricePlanEventData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PricePlanEventData")
    public JAXBElement<PricePlanEventData> createPricePlanEventData(PricePlanEventData value) {
        return new JAXBElement<PricePlanEventData>(_PricePlanEventData_QNAME, PricePlanEventData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantityRangeChargeData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityRangeChargeData")
    public JAXBElement<QuantityRangeChargeData> createQuantityRangeChargeData(QuantityRangeChargeData value) {
        return new JAXBElement<QuantityRangeChargeData>(_QuantityRangeChargeData_QNAME, QuantityRangeChargeData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfferDeleted")
    public JAXBElement<OfferDeleted> createOfferDeleted(OfferDeleted value) {
        return new JAXBElement<OfferDeleted>(_OfferDeleted_QNAME, OfferDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServicePricePlanCreated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServicePricePlanCreated")
    public JAXBElement<ServicePricePlanCreated> createServicePricePlanCreated(ServicePricePlanCreated value) {
        return new JAXBElement<ServicePricePlanCreated>(_ServicePricePlanCreated_QNAME, ServicePricePlanCreated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateUserSubscriptionWithCreditLimitRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateUserSubscriptionWithCreditLimitRequest")
    public JAXBElement<CreateUserSubscriptionWithCreditLimitRequest> createCreateUserSubscriptionWithCreditLimitRequest(CreateUserSubscriptionWithCreditLimitRequest value) {
        return new JAXBElement<CreateUserSubscriptionWithCreditLimitRequest>(_CreateUserSubscriptionWithCreditLimitRequest_QNAME, CreateUserSubscriptionWithCreditLimitRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferPricePlanUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfferPricePlanUpdated")
    public JAXBElement<OfferPricePlanUpdated> createOfferPricePlanUpdated(OfferPricePlanUpdated value) {
        return new JAXBElement<OfferPricePlanUpdated>(_OfferPricePlanUpdated_QNAME, OfferPricePlanUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PlaceOrderRequest")
    public JAXBElement<PlaceOrderRequest> createPlaceOrderRequest(PlaceOrderRequest value) {
        return new JAXBElement<PlaceOrderRequest>(_PlaceOrderRequest_QNAME, PlaceOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateOrganizationSubscriptionWithCreditLimitRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdateOrganizationSubscriptionWithCreditLimitRequest")
    public JAXBElement<UpdateOrganizationSubscriptionWithCreditLimitRequest> createUpdateOrganizationSubscriptionWithCreditLimitRequest(UpdateOrganizationSubscriptionWithCreditLimitRequest value) {
        return new JAXBElement<UpdateOrganizationSubscriptionWithCreditLimitRequest>(_UpdateOrganizationSubscriptionWithCreditLimitRequest_QNAME, UpdateOrganizationSubscriptionWithCreditLimitRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseEventData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BaseEventData")
    public JAXBElement<BaseEventData> createBaseEventData(BaseEventData value) {
        return new JAXBElement<BaseEventData>(_BaseEventData_QNAME, BaseEventData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminateOrganizationSubscriptionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TerminateOrganizationSubscriptionRequest")
    public JAXBElement<TerminateOrganizationSubscriptionRequest> createTerminateOrganizationSubscriptionRequest(TerminateOrganizationSubscriptionRequest value) {
        return new JAXBElement<TerminateOrganizationSubscriptionRequest>(_TerminateOrganizationSubscriptionRequest_QNAME, TerminateOrganizationSubscriptionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceEventData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceEventData")
    public JAXBElement<ServiceEventData> createServiceEventData(ServiceEventData value) {
        return new JAXBElement<ServiceEventData>(_ServiceEventData_QNAME, ServiceEventData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceSubscriptionDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceSubscriptionDate")
    public JAXBElement<ServiceSubscriptionDate> createServiceSubscriptionDate(ServiceSubscriptionDate value) {
        return new JAXBElement<ServiceSubscriptionDate>(_ServiceSubscriptionDate_QNAME, ServiceSubscriptionDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelUserSubscriptionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CancelUserSubscriptionRequest")
    public JAXBElement<CancelUserSubscriptionRequest> createCancelUserSubscriptionRequest(CancelUserSubscriptionRequest value) {
        return new JAXBElement<CancelUserSubscriptionRequest>(_CancelUserSubscriptionRequest_QNAME, CancelUserSubscriptionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserEventData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserEventData")
    public JAXBElement<UserEventData> createUserEventData(UserEventData value) {
        return new JAXBElement<UserEventData>(_UserEventData_QNAME, UserEventData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegionDeleted")
    public JAXBElement<RegionDeleted> createRegionDeleted(RegionDeleted value) {
        return new JAXBElement<RegionDeleted>(_RegionDeleted_QNAME, RegionDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsageRangeChargeData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UsageRangeChargeData")
    public JAXBElement<UsageRangeChargeData> createUsageRangeChargeData(UsageRangeChargeData value) {
        return new JAXBElement<UsageRangeChargeData>(_UsageRangeChargeData_QNAME, UsageRangeChargeData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemDescriptionData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ItemDescriptionData")
    public JAXBElement<ItemDescriptionData> createItemDescriptionData(ItemDescriptionData value) {
        return new JAXBElement<ItemDescriptionData>(_ItemDescriptionData_QNAME, ItemDescriptionData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceDeleted")
    public JAXBElement<ServiceDeleted> createServiceDeleted(ServiceDeleted value) {
        return new JAXBElement<ServiceDeleted>(_ServiceDeleted_QNAME, ServiceDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargePriceData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargePriceData")
    public JAXBElement<ChargePriceData> createChargePriceData(ChargePriceData value) {
        return new JAXBElement<ChargePriceData>(_ChargePriceData_QNAME, ChargePriceData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationCreated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OrganizationCreated")
    public JAXBElement<OrganizationCreated> createOrganizationCreated(OrganizationCreated value) {
        return new JAXBElement<OrganizationCreated>(_OrganizationCreated_QNAME, OrganizationCreated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateSubscriptionWithCreditLimitResponseBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdateSubscriptionWithCreditLimitResponseBase")
    public JAXBElement<UpdateSubscriptionWithCreditLimitResponseBase> createUpdateSubscriptionWithCreditLimitResponseBase(UpdateSubscriptionWithCreditLimitResponseBase value) {
        return new JAXBElement<UpdateSubscriptionWithCreditLimitResponseBase>(_UpdateSubscriptionWithCreditLimitResponseBase_QNAME, UpdateSubscriptionWithCreditLimitResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateUserSubscriptionWithCreditLimitResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateUserSubscriptionWithCreditLimitResponse")
    public JAXBElement<CreateUserSubscriptionWithCreditLimitResponse> createCreateUserSubscriptionWithCreditLimitResponse(CreateUserSubscriptionWithCreditLimitResponse value) {
        return new JAXBElement<CreateUserSubscriptionWithCreditLimitResponse>(_CreateUserSubscriptionWithCreditLimitResponse_QNAME, CreateUserSubscriptionWithCreditLimitResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemNameData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ItemNameData")
    public JAXBElement<ItemNameData> createItemNameData(ItemNameData value) {
        return new JAXBElement<ItemNameData>(_ItemNameData_QNAME, ItemNameData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminationChargeData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TerminationChargeData")
    public JAXBElement<TerminationChargeData> createTerminationChargeData(TerminationChargeData value) {
        return new JAXBElement<TerminationChargeData>(_TerminationChargeData_QNAME, TerminationChargeData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelOrganizationSubscriptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CancelOrganizationSubscriptionResponse")
    public JAXBElement<CancelOrganizationSubscriptionResponse> createCancelOrganizationSubscriptionResponse(CancelOrganizationSubscriptionResponse value) {
        return new JAXBElement<CancelOrganizationSubscriptionResponse>(_CancelOrganizationSubscriptionResponse_QNAME, CancelOrganizationSubscriptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminateSubscriptionRequestBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TerminateSubscriptionRequestBase")
    public JAXBElement<TerminateSubscriptionRequestBase> createTerminateSubscriptionRequestBase(TerminateSubscriptionRequestBase value) {
        return new JAXBElement<TerminateSubscriptionRequestBase>(_TerminateSubscriptionRequestBase_QNAME, TerminateSubscriptionRequestBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelUserSubscriptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CancelUserSubscriptionResponse")
    public JAXBElement<CancelUserSubscriptionResponse> createCancelUserSubscriptionResponse(CancelUserSubscriptionResponse value) {
        return new JAXBElement<CancelUserSubscriptionResponse>(_CancelUserSubscriptionResponse_QNAME, CancelUserSubscriptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxEventData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TaxEventData")
    public JAXBElement<TaxEventData> createTaxEventData(TaxEventData value) {
        return new JAXBElement<TaxEventData>(_TaxEventData_QNAME, TaxEventData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MutexItemData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MutexItemData")
    public JAXBElement<MutexItemData> createMutexItemData(MutexItemData value) {
        return new JAXBElement<MutexItemData>(_MutexItemData_QNAME, MutexItemData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserCreated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserCreated")
    public JAXBElement<UserCreated> createUserCreated(UserCreated value) {
        return new JAXBElement<UserCreated>(_UserCreated_QNAME, UserCreated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TaxData")
    public JAXBElement<TaxData> createTaxData(TaxData value) {
        return new JAXBElement<TaxData>(_TaxData_QNAME, TaxData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateUserSubscriptionWithCreditLimitRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdateUserSubscriptionWithCreditLimitRequest")
    public JAXBElement<UpdateUserSubscriptionWithCreditLimitRequest> createUpdateUserSubscriptionWithCreditLimitRequest(UpdateUserSubscriptionWithCreditLimitRequest value) {
        return new JAXBElement<UpdateUserSubscriptionWithCreditLimitRequest>(_UpdateUserSubscriptionWithCreditLimitRequest_QNAME, UpdateUserSubscriptionWithCreditLimitRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfferUpdated")
    public JAXBElement<OfferUpdated> createOfferUpdated(OfferUpdated value) {
        return new JAXBElement<OfferUpdated>(_OfferUpdated_QNAME, OfferUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminateSubscriptionResponseBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TerminateSubscriptionResponseBase")
    public JAXBElement<TerminateSubscriptionResponseBase> createTerminateSubscriptionResponseBase(TerminateSubscriptionResponseBase value) {
        return new JAXBElement<TerminateSubscriptionResponseBase>(_TerminateSubscriptionResponseBase_QNAME, TerminateSubscriptionResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionCreated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegionCreated")
    public JAXBElement<RegionCreated> createRegionCreated(RegionCreated value) {
        return new JAXBElement<RegionCreated>(_RegionCreated_QNAME, RegionCreated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateSubscriptionWithCreditLimitResponseBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateSubscriptionWithCreditLimitResponseBase")
    public JAXBElement<CreateSubscriptionWithCreditLimitResponseBase> createCreateSubscriptionWithCreditLimitResponseBase(CreateSubscriptionWithCreditLimitResponseBase value) {
        return new JAXBElement<CreateSubscriptionWithCreditLimitResponseBase>(_CreateSubscriptionWithCreditLimitResponseBase_QNAME, CreateSubscriptionWithCreditLimitResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServicePricePlanDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServicePricePlanDeleted")
    public JAXBElement<ServicePricePlanDeleted> createServicePricePlanDeleted(ServicePricePlanDeleted value) {
        return new JAXBElement<ServicePricePlanDeleted>(_ServicePricePlanDeleted_QNAME, ServicePricePlanDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminateUserSubscriptionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TerminateUserSubscriptionRequest")
    public JAXBElement<TerminateUserSubscriptionRequest> createTerminateUserSubscriptionRequest(TerminateUserSubscriptionRequest value) {
        return new JAXBElement<TerminateUserSubscriptionRequest>(_TerminateUserSubscriptionRequest_QNAME, TerminateUserSubscriptionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsageChargeData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UsageChargeData")
    public JAXBElement<UsageChargeData> createUsageChargeData(UsageChargeData value) {
        return new JAXBElement<UsageChargeData>(_UsageChargeData_QNAME, UsageChargeData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecurringChargeData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RecurringChargeData")
    public JAXBElement<RecurringChargeData> createRecurringChargeData(RecurringChargeData value) {
        return new JAXBElement<RecurringChargeData>(_RecurringChargeData_QNAME, RecurringChargeData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminateUserSubscriptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TerminateUserSubscriptionResponse")
    public JAXBElement<TerminateUserSubscriptionResponse> createTerminateUserSubscriptionResponse(TerminateUserSubscriptionResponse value) {
        return new JAXBElement<TerminateUserSubscriptionResponse>(_TerminateUserSubscriptionResponse_QNAME, TerminateUserSubscriptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeBaseData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeBaseData")
    public JAXBElement<ChargeBaseData> createChargeBaseData(ChargeBaseData value) {
        return new JAXBElement<ChargeBaseData>(_ChargeBaseData_QNAME, ChargeBaseData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrganizationSubscriptionWithCreditLimitResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateOrganizationSubscriptionWithCreditLimitResponse")
    public JAXBElement<CreateOrganizationSubscriptionWithCreditLimitResponse> createCreateOrganizationSubscriptionWithCreditLimitResponse(CreateOrganizationSubscriptionWithCreditLimitResponse value) {
        return new JAXBElement<CreateOrganizationSubscriptionWithCreditLimitResponse>(_CreateOrganizationSubscriptionWithCreditLimitResponse_QNAME, CreateOrganizationSubscriptionWithCreditLimitResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelSubscriptionRequestBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CancelSubscriptionRequestBase")
    public JAXBElement<CancelSubscriptionRequestBase> createCancelSubscriptionRequestBase(CancelSubscriptionRequestBase value) {
        return new JAXBElement<CancelSubscriptionRequestBase>(_CancelSubscriptionRequestBase_QNAME, CancelSubscriptionRequestBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationEventData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OrganizationEventData")
    public JAXBElement<OrganizationEventData> createOrganizationEventData(OrganizationEventData value) {
        return new JAXBElement<OrganizationEventData>(_OrganizationEventData_QNAME, OrganizationEventData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateSubscriptionWithCreditLimitRequestBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdateSubscriptionWithCreditLimitRequestBase")
    public JAXBElement<UpdateSubscriptionWithCreditLimitRequestBase> createUpdateSubscriptionWithCreditLimitRequestBase(UpdateSubscriptionWithCreditLimitRequestBase value) {
        return new JAXBElement<UpdateSubscriptionWithCreditLimitRequestBase>(_UpdateSubscriptionWithCreditLimitRequestBase_QNAME, UpdateSubscriptionWithCreditLimitRequestBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserUpdated")
    public JAXBElement<UserUpdated> createUserUpdated(UserUpdated value) {
        return new JAXBElement<UserUpdated>(_UserUpdated_QNAME, UserUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateSubscriptionWithCreditLimitRequestBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateSubscriptionWithCreditLimitRequestBase")
    public JAXBElement<CreateSubscriptionWithCreditLimitRequestBase> createCreateSubscriptionWithCreditLimitRequestBase(CreateSubscriptionWithCreditLimitRequestBase value) {
        return new JAXBElement<CreateSubscriptionWithCreditLimitRequestBase>(_CreateSubscriptionWithCreditLimitRequestBase_QNAME, CreateSubscriptionWithCreditLimitRequestBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegionUpdated")
    public JAXBElement<RegionUpdated> createRegionUpdated(RegionUpdated value) {
        return new JAXBElement<RegionUpdated>(_RegionUpdated_QNAME, RegionUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferCreated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfferCreated")
    public JAXBElement<OfferCreated> createOfferCreated(OfferCreated value) {
        return new JAXBElement<OfferCreated>(_OfferCreated_QNAME, OfferCreated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferPricePlanCreated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfferPricePlanCreated")
    public JAXBElement<OfferPricePlanCreated> createOfferPricePlanCreated(OfferPricePlanCreated value) {
        return new JAXBElement<OfferPricePlanCreated>(_OfferPricePlanCreated_QNAME, OfferPricePlanCreated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TaxUpdated")
    public JAXBElement<TaxUpdated> createTaxUpdated(TaxUpdated value) {
        return new JAXBElement<TaxUpdated>(_TaxUpdated_QNAME, TaxUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionEventData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegionEventData")
    public JAXBElement<RegionEventData> createRegionEventData(RegionEventData value) {
        return new JAXBElement<RegionEventData>(_RegionEventData_QNAME, RegionEventData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrganizationSubscriptionWithCreditLimitRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateOrganizationSubscriptionWithCreditLimitRequest")
    public JAXBElement<CreateOrganizationSubscriptionWithCreditLimitRequest> createCreateOrganizationSubscriptionWithCreditLimitRequest(CreateOrganizationSubscriptionWithCreditLimitRequest value) {
        return new JAXBElement<CreateOrganizationSubscriptionWithCreditLimitRequest>(_CreateOrganizationSubscriptionWithCreditLimitRequest_QNAME, CreateOrganizationSubscriptionWithCreditLimitRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelSubscriptionResponseBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CancelSubscriptionResponseBase")
    public JAXBElement<CancelSubscriptionResponseBase> createCancelSubscriptionResponseBase(CancelSubscriptionResponseBase value) {
        return new JAXBElement<CancelSubscriptionResponseBase>(_CancelSubscriptionResponseBase_QNAME, CancelSubscriptionResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceUpdated")
    public JAXBElement<ServiceUpdated> createServiceUpdated(ServiceUpdated value) {
        return new JAXBElement<ServiceUpdated>(_ServiceUpdated_QNAME, ServiceUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelOrganizationSubscriptionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CancelOrganizationSubscriptionRequest")
    public JAXBElement<CancelOrganizationSubscriptionRequest> createCancelOrganizationSubscriptionRequest(CancelOrganizationSubscriptionRequest value) {
        return new JAXBElement<CancelOrganizationSubscriptionRequest>(_CancelOrganizationSubscriptionRequest_QNAME, CancelOrganizationSubscriptionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OrganizationDeleted")
    public JAXBElement<OrganizationDeleted> createOrganizationDeleted(OrganizationDeleted value) {
        return new JAXBElement<OrganizationDeleted>(_OrganizationDeleted_QNAME, OrganizationDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateUserSubscriptionWithCreditLimitResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdateUserSubscriptionWithCreditLimitResponse")
    public JAXBElement<UpdateUserSubscriptionWithCreditLimitResponse> createUpdateUserSubscriptionWithCreditLimitResponse(UpdateUserSubscriptionWithCreditLimitResponse value) {
        return new JAXBElement<UpdateUserSubscriptionWithCreditLimitResponse>(_UpdateUserSubscriptionWithCreditLimitResponse_QNAME, UpdateUserSubscriptionWithCreditLimitResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationCreditLimit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OrganizationCreditLimit")
    public JAXBElement<OrganizationCreditLimit> createOrganizationCreditLimit(OrganizationCreditLimit value) {
        return new JAXBElement<OrganizationCreditLimit>(_OrganizationCreditLimit_QNAME, OrganizationCreditLimit.class, null, value);
    }

}
