//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 10:15:44 AM CST 
//


package org.meveo.asg.api.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfferEventData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfferEventData">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseEventData">
 *       &lt;sequence>
 *         &lt;element name="OfferId" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CategoryId" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="OrganizationId" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="IsOrganizationOffer" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Descriptions" type="{}ArrayOfItemDescriptionData" minOccurs="0"/>
 *         &lt;element name="Services" type="{}ArrayOfServiceItemData" minOccurs="0"/>
 *         &lt;element name="MutexGroups" type="{}ArrayOfMutexItemData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfferEventData", propOrder = {
    "offerId",
    "code",
    "categoryId",
    "organizationId",
    "isOrganizationOffer",
    "descriptions",
    "services",
    "mutexGroups"
})
public class OfferEventData
    extends BaseEventData
{

    @XmlElement(name = "OfferId", required = true)
    protected String offerId;
    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "CategoryId", required = true, nillable = true)
    protected String categoryId;
    @XmlElement(name = "OrganizationId", required = true)
    protected String organizationId;
    @XmlElement(name = "IsOrganizationOffer")
    protected boolean isOrganizationOffer;
    @XmlElement(name = "Descriptions")
    protected ArrayOfItemDescriptionData descriptions;
    @XmlElement(name = "Services")
    protected ArrayOfServiceItemData services;
    @XmlElement(name = "MutexGroups")
    protected ArrayOfMutexItemData mutexGroups;

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferId(String value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the categoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * Sets the value of the categoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryId(String value) {
        this.categoryId = value;
    }

    /**
     * Gets the value of the organizationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * Sets the value of the organizationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationId(String value) {
        this.organizationId = value;
    }

    /**
     * Gets the value of the isOrganizationOffer property.
     * 
     */
    public boolean isIsOrganizationOffer() {
        return isOrganizationOffer;
    }

    /**
     * Sets the value of the isOrganizationOffer property.
     * 
     */
    public void setIsOrganizationOffer(boolean value) {
        this.isOrganizationOffer = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfItemDescriptionData }
     *     
     */
    public ArrayOfItemDescriptionData getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemDescriptionData }
     *     
     */
    public void setDescriptions(ArrayOfItemDescriptionData value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfServiceItemData }
     *     
     */
    public ArrayOfServiceItemData getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfServiceItemData }
     *     
     */
    public void setServices(ArrayOfServiceItemData value) {
        this.services = value;
    }

    /**
     * Gets the value of the mutexGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMutexItemData }
     *     
     */
    public ArrayOfMutexItemData getMutexGroups() {
        return mutexGroups;
    }

    /**
     * Sets the value of the mutexGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMutexItemData }
     *     
     */
    public void setMutexGroups(ArrayOfMutexItemData value) {
        this.mutexGroups = value;
    }

}
