//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 08:46:55 PM CST 
//


package org.meveo.asg.api.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriptionAgeRangeChargeData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionAgeRangeChargeData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Min" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Max" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Prices" type="{}ArrayOfChargePriceData" minOccurs="0"/>
 *         &lt;element name="QuantityRangeCharges" type="{}ArrayOfQuantityRangeChargeData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionAgeRangeChargeData", propOrder = {
    "min",
    "max",
    "prices",
    "quantityRangeCharges"
})
public class SubscriptionAgeRangeChargeData {

    @XmlElement(name = "Min", required = true, type = Integer.class, nillable = true)
    protected Integer min;
    @XmlElement(name = "Max", required = true, type = Integer.class, nillable = true)
    protected Integer max;
    @XmlElement(name = "Prices")
    protected ArrayOfChargePriceData prices;
    @XmlElement(name = "QuantityRangeCharges")
    protected ArrayOfQuantityRangeChargeData quantityRangeCharges;

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMin(Integer value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMax(Integer value) {
        this.max = value;
    }

    /**
     * Gets the value of the prices property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfChargePriceData }
     *     
     */
    public ArrayOfChargePriceData getPrices() {
        return prices;
    }

    /**
     * Sets the value of the prices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfChargePriceData }
     *     
     */
    public void setPrices(ArrayOfChargePriceData value) {
        this.prices = value;
    }

    /**
     * Gets the value of the quantityRangeCharges property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfQuantityRangeChargeData }
     *     
     */
    public ArrayOfQuantityRangeChargeData getQuantityRangeCharges() {
        return quantityRangeCharges;
    }

    /**
     * Sets the value of the quantityRangeCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfQuantityRangeChargeData }
     *     
     */
    public void setQuantityRangeCharges(ArrayOfQuantityRangeChargeData value) {
        this.quantityRangeCharges = value;
    }

}
