//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 10:15:44 AM CST 
//


package org.meveo.asg.api.dto;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxEventData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxEventData">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseEventData">
 *       &lt;sequence>
 *         &lt;element name="TaxId" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="RegionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountryIsoCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Descriptions" type="{}ArrayOfItemDescriptionData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxEventData", propOrder = {
    "taxId",
    "regionCode",
    "countryIsoCode",
    "percentage",
    "descriptions"
})
public class TaxEventData
    extends BaseEventData
{

    @XmlElement(name = "TaxId", required = true)
    protected String taxId;
    @XmlElement(name = "RegionCode")
    protected String regionCode;
    @XmlElement(name = "CountryIsoCode")
    protected int countryIsoCode;
    @XmlElement(name = "Percentage", required = true)
    protected BigDecimal percentage;
    @XmlElement(name = "Descriptions")
    protected ArrayOfItemDescriptionData descriptions;

    /**
     * Gets the value of the taxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxId() {
        return taxId;
    }

    /**
     * Sets the value of the taxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxId(String value) {
        this.taxId = value;
    }

    /**
     * Gets the value of the regionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * Sets the value of the regionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionCode(String value) {
        this.regionCode = value;
    }

    /**
     * Gets the value of the countryIsoCode property.
     * 
     */
    public int getCountryIsoCode() {
        return countryIsoCode;
    }

    /**
     * Sets the value of the countryIsoCode property.
     * 
     */
    public void setCountryIsoCode(int value) {
        this.countryIsoCode = value;
    }

    /**
     * Gets the value of the percentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentage() {
        return percentage;
    }

    /**
     * Sets the value of the percentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentage(BigDecimal value) {
        this.percentage = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfItemDescriptionData }
     *     
     */
    public ArrayOfItemDescriptionData getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemDescriptionData }
     *     
     */
    public void setDescriptions(ArrayOfItemDescriptionData value) {
        this.descriptions = value;
    }

}
